### ISSUE TITLE
Possible bug in tracker.js

### ISSUE THREAD

**Issue by MichaelRoosz** [sgiehl/piwik-plugin-DeviceFeatureWebGL#1]
https://github.com/sgiehl/piwik-plugin-DeviceFeatureWebGL/blob/4da6936ba4de997373e01d4a48cd2bd8a779ce5d/tracker.js#L20

I forked your plugin and I cannot get the tracker.js code to work.
Could this be a bug?
As I understand it, these checks should be removed:
```
        if ('object' === typeof window && 'object' === typeof window.Piwik) {
            // do not initialize twice
            return;
        }

        if ('object' === typeof window && !window.Piwik) {
            // piwik is not defined yet
            return;
        }
```

**Comment by sgiehl** [comment]
Seems you are right. Will check and update the plugin later

**Comment by sgiehl** [comment]
Updated it and released a new version

**Comment by MichaelRoosz** [comment]
Thanks a lot !
