### ISSUE TITLE
Matomo JS tracker file not updated

### ISSUE THREAD

**Issue by danielkurecka** [sgiehl/piwik-plugin-DeviceFeatureWebGL#2]
Matomo checks every hour if matomo.js needs to be regenerated. However this plugin's tracker.js is never added to it.

I was able to fix it by adding following method to `Piwik\Plugins\DeviceFeatureWebG\DeviceFeatureWebGL` class:

```php
public function isTrackerPlugin()
{
    return true;
}
```

**Comment by sgiehl** [comment]
Cheers. Updated it and released a new version
